#ifndef COMMAND_H
#define COMMAND_H

#define ENABLE_DEVICE "C01:1\r"
#define DISABLE_DEVICE "C01:0\r"

#define ENABLE_DATA_TRANSFER "C02:1\r"
#define DISABLE_DATA_TRANSFER "C02:0\r"

#define VOLTAGE_AND_CURRENT "C03:V1;I1\r"
#define ONLY_VOLTAGE "C03:V1;I0\r"

#define READ_DATA "C04:1\r"

#endif // COMMAND_H
